[build]
  command = "pnpm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  PNPM_VERSION = "9"
  # Skip better-sqlite3 compilation for static builds
  CONTENT_DATABASE_TYPE = "libsql"
  CONTENT_DATABASE_URL = ":memory:"

[[plugins]]
  package = "@netlify/plugin-caching"
